### ISSUE TITLE
code throw exception on emscripten mode

### ISSUE THREAD

**Issue by xueyouchao** [floooh/fips#122]
Hi,Andre
I wrote a test code for compile-time hash string, it compiles and and runs well on default config (win64-vstudio-debug) but threw exception on emscripten mode. (getstreamfromptr of undefined) I didn't load any external file and don't know why the exception happens.

It also builds and runs well if I build separately using em++ CompileTimeString.cc.

I attached code below, could you take a look?

thank you

[test.zip](https://github.com/floooh/fips/files/172657/test.zip)

**Comment by floooh** [comment]
I guess this is because fips has the EMSCRIPTEN_NO_FILESYSTEM option enabled by default to reduce the output size, and std::cout doesn't work. However I could not reproduce the problem with the current emscripten version on the incoming branch. Your code compiles fine and prints a "lala" in the browser text field, so I guess it works. 

Can you try updating to the latest emscripten incoming version? If not you could try using printf() instead of std::cout, or set the cmake option FIPS_EMSCRIPTEN_USE_FS via "fips config".

**Comment by floooh** [comment]
Oh wait, you're on Windows right. This makes it a little more complicated... since for Windows, fips doesn't install the latest incoming version by default, but currently 1.34.1 which is fairly old (current is 1.36.1 I think). 

To update manually, go to ../fips-sdks/win/emsdk_portable/ and run 'emsdk' to update to the latest version (the details are here: https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html), basically you would need to do this:

```
> emsdk update
> emsdk install latest
> emsdk activate latest
```

Good luck :)

**Comment by xueyouchao** [comment]
Thanks so much, it works once I used printf to replace std::cout. I guess it's something to do with the FIPS_EMSCRIPTEN_USE_FS. I tried fips config to config it in cmake but seems get some error about exception pre-processor.
ERROR    root: /EHa: No such file or directory ("/EHa" was expected to be an input file, based on the commandline arguments provided)

But I guess as long as I stay away with stl; there is no problem.
