### ISSUE TITLE
Space in Source Directory Path Confuses Fips

### ISSUE THREAD

**Issue by ubaldy** [floooh/fips#231]
If there is a space in the path on Windows using Git Bash, it confuses Fips and it does not properly parse the paths. Though I could just be doing something stupid. It works if I move workspace directly under C:/

CMake Error: The source directory "C:/Users/John Smith/workspace/fips-build/procedural_swarm/win64-vs2017-release/Smith/workspace/procedural_swarm" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
[ERROR] Failed to generate 'win64-vs2017-release' of project 'procedural_swarm'

**Comment by floooh** [comment]
Yes, unfortunately that's the case, I have been looking into this a little while ago, it's also 3rd-party-tools which are confused by spaces in paths, and it's almost impossible to properly escape spaces in paths when invoking tools from python via the system shell, since different shells and operating systems behave differently.

In the end I decided to just add a warning (you should've seen this further up the console output).

Here's the commnit which added the warning: https://github.com/floooh/fips/commit/b9bc5732804a59d70b916faed657ec097fb765c9
