### ISSUE TITLE
fips diag tools for checking http-server???

### ISSUE THREAD

**Issue by Ron2014** [floooh/fips#248]
Hi ya, master!

[look this file](https://github.com/floooh/fips/blob/master/mod/tools/httpserver.py)

I'm wandering about the code above: 

why use ' make -h' to check node's http-server module ?

```
def check_exists(fips_dir) :
    try:
        out = subprocess.check_output(['make', '-h'])
        return True
    except (OSError, subprocess.CalledProcessError):
        return False
```

Quite cound not get the relationship between 'make -h' and httpserver :-)

PS. I really want to know the tools version when I use 'fips diag tools'.

When I built a project (like curl+openssl) use 'cmake . ' directly, I found different result between intergrating them into my project and using 'fips build', for locating the factor, return the version of cmake and other tools in command 'fips diag tools' will be helpful.

**Comment by Ron2014** [comment]
I'v changed mod/tools/*.py to print what I want. Just for advice about return value of function 'check_exists'

**Comment by floooh** [comment]
Hi, thanks for spotting the 'make -h' bug, I guess that was a copy-paste error. I'll think about displaying the version, but it'll be quite a bit of work to implement for all checked tools since they all have different formatting for the version output string, and some tools don't have a way to query a version at all.
