### ISSUE TITLE
Is this FIPS possible to support VS2010 project?

### ISSUE THREAD

**Issue by Ron2014** [floooh/fips#254]
Hi, master. These days I'm reading [Programming Game AI by Example](https://www.jblearning.com/catalog/productdetails/9781556220784#productInfo) and I'm working in the demos now (see the [SAMPLE MATERIALS]/[Source Code] in the URL), trying to build them with FIPS.

The newest demo project is vs2010 and mostly can work fine with FIPS and vs2017(my development environment). FIPS is fantastic.

What make me feel hard is the luabind demo. luabind is combined with lua-5.1.3 luabind-?? and boost-??. When I use the latest version boost_1_72_0, I got Error C2665

```
E:\GitHub\Programming_Game_AI_by_Example\code\Common\luabind\luabind/object.hpp(556): error C2665: 'boost::operator ==': none of the 4 overloads could convert all the argument  
types (compiling source file E:\GitHub\Programming_Game_AI_by_Example\code\Buckland_Chapter6_Scripting_Source\ScriptedStateMachine\main.cpp) [E:\GitHub\Programming_Game_AI_by_E 
xample\fips-build\code\win_d\Buckland_Chapter6_Scripting_Source\ScriptedStateMachine.vcxproj]
```

To fix this error, I found the best way is using the matched version of boost, like boost_1_48_0 published in 2011. So there is no building script for vs2017 in boost_1_48_0.

Everything tell me I need install VS2010 and build the boost, then  build luabind demo.

BUT...

I check the fips/config/*.yml, find the oldest version for building in windows is winXX-vs2013-XXX.yml.

So, that is where the title question come from:  Is this FIPS possible to support VS2010 project?

If possible, I want to give it try.

**Comment by Ron2014** [comment]
[I have made a try](https://github.com/Ron2014/Programming_Game_AI_by_Example).

Build the boost_1_48_0 with VS2010 by it's original building script, then I get the include&library path which luabind need.

And I build luabind demo with fips using VS2017 compiler. It works.

**Comment by floooh** [comment]
Hi, by using the ```*-vstudio-*``` build configurations instead of one of the specific ```*-vs2017-*``` (etc), fips should select the "default Visual Studio version" on your system (so if you only have VS2010 installed, it should pick this).

An alternative is to add local build-config files to your main project (like here in the sokol-samples: https://github.com/floooh/sokol-samples/tree/master/fips-files/configs), copy one of the ```*-vs2017-*``` configs from fips to your project directory (under fips-files/configs) and then change the cmake generator to ```Visual Studio 10 2010```:

https://github.com/floooh/sokol-samples/blob/31f09afcbb0ebcff75b19a31ba63e68eb5cba42c/fips-files/configs/sapp-d3d11-win64-vs2015-debug.yml#L3
