### ISSUE TITLE
Ios Bundle assets and other Xcode settings

### ISSUE THREAD

**Issue by Hperigo** [floooh/fips#259]
Hey there.
I have a couple of somewhat basic questions:

1. How can I move assets ( images, text, scripts, etc) to the to the compiled IOS app?
I know you mentioned on this issue that I should use this generator: [https://github.com/floooh/fips/issues/187](https://github.com/floooh/fips/issues/187)

But do you have any pointers on how to do it with an MacApp and iOS app? 

2. How can I change Xcode build settings? for example every time I do `./fips gen` I need to change the **Architectures** from armv7 arm64 x86_64..  to $(ARCHS_STANDARD)

**Comment by floooh** [comment]
Hi, for copying asset files I'd recommend using the (somewhat new) scripts in the fips_utils project:

https://github.com/fips-libs/fips-utils

The fipsutil_copy() macro accepts iOS and macOS specific overrides for the destination directory, so that you can place the asset files into the right bundle subdirectory:

https://github.com/fips-libs/fips-utils/blob/7703b78914aea29910abd3c5242dd2ab4e64231c/fips-files/generators/copy.py#L13-L17

I'm surprised that editing the Architectures Xcode build setting is necessary, what sort of error are you getting?

The value is defined in fips here:

https://github.com/floooh/fips/blob/6fff11c39c60178fd9987913a5684c317bc4db61/cmake-toolchains/ios.toolchain.cmake#L16

You can override the ios.toolchain.cmake file in your own project (basically copy the file from fips into your own project, and modify it as needed), how this works is described here:

https://floooh.github.io/fips/docs/crosscompiling/#under-the-hood

I'll close the issue, if there are any more questions or something isn't working, just open it again :)

**Comment by Hperigo** [comment]
Hi, thanks for the reply and information =)

This is the error that I was getting, I think it started after I updated my mac to Catalina: 
<img width="467" alt="Screen Shot 2020-06-15 at 6 26 30 PM" src="https://user-images.githubusercontent.com/3333460/84718301-a17f3600-af4e-11ea-9c6d-7f3dd9a2e344.png">

**Comment by floooh** [comment]
> This is the error that I was getting, I think it started after I updated my mac to Catalina:

I remember seeing a similar error message too, but the problem went away after doing a "fips clean" and "fips gen" again (so basically regenerating the Xcode project files from scratch), so I shrugged it off so far.

It might make sense to remove armv7 from the architectures list though, since 32-bit apps are no longer supported anyway (AFAIK at least).
