### ISSUE TITLE
Using the generators doesn't work on new files

### ISSUE THREAD

**Issue by mgerhardy** [floooh/fips#41]
Maybe I did something wrong, but for me it looks like generating a file from a python script relies on the header file to already exist.

  File "/home/mgerhardy/dev/fips/generators/genutil.py", line 65, in isDirty
    if fileVersionDirty(dstSrcPath, version) or fileVersionDirty(dstHdrPath, version) :
  File "/home/mgerhardy/dev/fips/generators/genutil.py", line 44, in fileVersionDirty
    f = open(filePath, 'r')

Getting an IOError telling me that my shaders.h file doesn't exist - which imo is fine, because the generator should just try to create it. I don't want to check that file (the header that should be generated) into version control.

**Comment by floooh** [comment]
The cmake script should generate a dummy .cc and .h file on ./fips gen (or any cmake run) if those don't exist yet (see here: https://github.com/floooh/fips/blob/master/cmake/fips_generators.cmake#L11), this seems to be necessary because cmake requires that all source files exist.

I'm currently rewriting the code generation stuff in the 'refactorgen' branch, so some things will change (most importantly the function signature of the python generate() functions, the details for this rewrite are here: #16 

I have tried to move the generated files out of the source tree so that it is easier to keep them out of version control, but this is tricky because of the header search path setup. Because C compiler searches first in the directory of the current source I would have to assign per-source-file search paths, I think cmake allows this but it's not very elegant.

Another option would be to automatically populate a local .gitignore file, but I don't like that solution either :/

**Comment by mgerhardy** [comment]
The advantage of having it in the source tree is that you could browse it more easily. There might be situations where you have to open a generated file. Also for example eclipse CDT does index only files that are part of the project. If you move it out of out of the project dir, you will never get something indexed.

I would vote for populating the .gitignore ;)

**Comment by floooh** [comment]
Ok, I'll try a few different solutions over the weekend... the generated files would still be available in IDE project browsers since they are part of the project, but not in normal text editors like vim...

**Comment by floooh** [comment]
I have merged the new code generation stuff (this is now handled through a new fips_generate() macro), and opened a new issue for not putting generated source files into version control.
