### ISSUE TITLE
SDL fipsified - but it needs a git command installed

### ISSUE THREAD

**Issue by mgerhardy** [floooh/fips#82]
https://github.com/mgerhardy/fips-sdl

I gave it another try - but sdl2 is using mercurial, not git - therefore you need to install https://github.com/mgerhardy/fips-sdl/blob/master/git-remote-hg in your path. Is there a better way to deal with it? Maybe install dedicated git modules - or put fips-git directories into the path in the git.py?

**Comment by mgerhardy** [comment]
btw... this might not yet work 100% - it's an ongoing effort and help is much appreciated ;)

**Comment by floooh** [comment]
I have a couple of ideas, but they require work on the low-level parts of fips...

First: I think it makes sense to add direct support for more version control systems besides git, I want to start using fips also for our Bigpoint C++ projects in the not-too-distant future, which would fetching dependencies from svn repos (another nice side effect would be that we could then start mixing git and svn projects, and move some of our projects over to git).

Second: provide an alternative to git submodules for 'fipsified projects' to include the original project. git submodules have a couple of problems when actually working with these fipsified projects (e.g. working on pull requests for upstream etc...)... I'm currently thinking that it would be useful to allow fetching non-fips projects as dependencies (I think I even already implemented this) so that the fips-wrapper would not "contain" the original project, but instead fetch this as a normal dependency...

Both of these combined (direct support for hg, and not including the original project as git submodule) would solve the problem of SDL not using git...

**Comment by mgerhardy** [comment]
Ok, then I will stop my work on fips-sdl (again) and wait for direct mercurial support (or provide a pull request once subversion is in and the basic support for more vcs is done)

btw. I still think that looking at MXE might help - we only build stable releases there. Which also has a lot of advantages. At BigPoint we could do the same with the artifactory. Generate a release archive and just download it via http might be better than supporting all the vcs's out there. And it also has the advantage to not break compilation if someone commits something for some reason.
